# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 'https://ryanguo1998.github.io'
baseurl:             'blog/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ryan Guo
  url:               
  email:             rguo98@uchicago.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
